### ISSUE TITLE
Add more features and more words in Array

### ISSUE THREAD

**Issue by prasad-chavan1** [prasad-chavan1/word-scramble-extension#1]
const words = [
    {
        "word": "pocket",
        "hint": "A bag for carrying small things"
    },
    {
        "word": "needle",
        "hint": "A thin & sharp metal pin"
    },
    {
        ......
        ........
        ...........
    }

**Comment by prasad-chavan1** [comment]
@sneha-4-22 Open this issue

**Comment by HarjjotSinghh** [comment]
heyy, I think I can add quite a few more words, can you please assign this issue to me?

**Comment by prasad-chavan1** [comment]
@HarjjotSinghh Raise a PR for that

**Comment by prasad-chavan1** [comment]
You can also open my new issues
