### ISSUE TITLE
Add API to fetch words and their hints

### ISSUE THREAD

**Issue by prasad-chavan1** [prasad-chavan1/word-scramble-extension#5]
**API Integration**
Hey folks, integrate api in this project instead of using words array. You can go with words api read their documentation

**Reference Link**
https://www.wordsapi.com/

**Comment by sneha-4-22** [comment]
i have one doubt
do we need to  using the words array in ourJavaScript code to get random words, then create our  own API that generates random words 
or
 any other api endpoints that are  online  for getting random words

**Comment by prasad-chavan1** [comment]
> i have one doubt do we need to using the words array in ourJavaScript code to get random words, then create our own API that generates random words or any other api endpoints that are online for getting random words

You can create your own api end points like json and use them here.. See this demo

**words.json**

```js
[
    {
        "word": "pocket",
        "hint": "A bag for carrying small things"
    },
    {
        "word": "needle",
        "hint": "A thin & sharp metal pin"
    },
    {
        "word": "expert",
        "hint": "Person with extensive knowledge"
    }
   .
   .
   .
]
```
Then upload it to any platform or on github and using endpoint link to fetch words....
for e.g. 
```shell
   https://raw.example.com/words.json
